{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-view",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.1.0-beta02.aar",
          "url": "camera-view-1.1.0-beta02.aar",
          "size": 88343,
          "sha512": "9dae7af0417acf2de157691d1e3f00ff9df08d965a26d2f5a0bbd370f63aa566f10d262b485bde131961f81b045f3e1f5cea7df5e2a4e95dcf4ef246968085b0",
          "sha256": "cecad075e2f106093dbf7494ddc13c601dc45630b61a656223172a266c5cdbab",
          "sha1": "dba46b08f6f630a92dfc235abf8351e8df28467e",
          "md5": "1c7bb60d2a98a808d6b6601b5a3549a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.1.0-beta02.aar",
          "url": "camera-view-1.1.0-beta02.aar",
          "size": 88343,
          "sha512": "9dae7af0417acf2de157691d1e3f00ff9df08d965a26d2f5a0bbd370f63aa566f10d262b485bde131961f81b045f3e1f5cea7df5e2a4e95dcf4ef246968085b0",
          "sha256": "cecad075e2f106093dbf7494ddc13c601dc45630b61a656223172a266c5cdbab",
          "sha1": "dba46b08f6f630a92dfc235abf8351e8df28467e",
          "md5": "1c7bb60d2a98a808d6b6601b5a3549a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-view-1.1.0-beta02-sources.jar",
          "url": "camera-view-1.1.0-beta02-sources.jar",
          "size": 71634,
          "sha512": "15456b42eb476ac01d7431c5111f3c14a8ba4989306c5a12e39ef2b9128ea6876053e87758a7b6a1271c78c854b34ebc0fda19bb7c3af3f0c28b576d41739fec",
          "sha256": "a06a0f0cbba6794a4a4c948efeb1f1f04a5dc0bd66ca7c45856f84327066f7b5",
          "sha1": "dfbe08963cf2b5e4890f6a69a80153996fd419df",
          "md5": "1815f6d3c8e2ee9dc2750454a1e867e9"
        }
      ]
    }
  ]
}
