{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-video",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "camera-video-1.1.0-beta02.aar",
          "url": "camera-video-1.1.0-beta02.aar",
          "size": 259418,
          "sha512": "0c2027026815dc9bf37bd3cf6d1d7b32d475a4e4d1e87d31ef9188d54f4e84e4743cd2a606d542ec40117f024421997f08672cde8041243961a2da6475482117",
          "sha256": "7729dab1735dfd8c05ae16a7b926fa625e6dc5ab6333fc2ebdbe2789624da5a7",
          "sha1": "a0e6e9a93e060e038743f92855d58c9e33853ed3",
          "md5": "21100c300ecbf162b02f5408b0cd6c3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-video-1.1.0-beta02.aar",
          "url": "camera-video-1.1.0-beta02.aar",
          "size": 259418,
          "sha512": "0c2027026815dc9bf37bd3cf6d1d7b32d475a4e4d1e87d31ef9188d54f4e84e4743cd2a606d542ec40117f024421997f08672cde8041243961a2da6475482117",
          "sha256": "7729dab1735dfd8c05ae16a7b926fa625e6dc5ab6333fc2ebdbe2789624da5a7",
          "sha1": "a0e6e9a93e060e038743f92855d58c9e33853ed3",
          "md5": "21100c300ecbf162b02f5408b0cd6c3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-video-1.1.0-beta02-sources.jar",
          "url": "camera-video-1.1.0-beta02-sources.jar",
          "size": 177020,
          "sha512": "1f522bf80f6aca76deb63535c138cf674dc61cede9622d6ddce2606a6d14a6065449ef4cf5fe4492c1fa31b6bc1244deb42c889a644ae69c61e1add028834e1e",
          "sha256": "7699a436adb8236918c38d4e5d88c49b3b5dc4b6b2399d30ddf37d15fa61adfd",
          "sha1": "ae687219fb03aac24c90ff68aa7e57dbbcb90632",
          "md5": "7b9f88d3e92c05e4ad974293d476f099"
        }
      ]
    }
  ]
}
