{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.1.0-beta02.aar",
          "url": "camera-lifecycle-1.1.0-beta02.aar",
          "size": 19278,
          "sha512": "5518081b3511ebab128e3ea842b6040a47e3a84192ad88f6b477414360806f36d3c2ae269b0a8da427d275eab0daeaaf419ff0ec310e27d1feb7c61772a9c4a9",
          "sha256": "71abe454726b78aedff49925f2cc792ed95152ccda32c7dfdbd6bc47cc70d091",
          "sha1": "19310a05446a2ad1a27d9abf3f4ec8ec63388c27",
          "md5": "93a6e3d579924ebe5dfaadd6b8a73cba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.1.0-beta02.aar",
          "url": "camera-lifecycle-1.1.0-beta02.aar",
          "size": 19278,
          "sha512": "5518081b3511ebab128e3ea842b6040a47e3a84192ad88f6b477414360806f36d3c2ae269b0a8da427d275eab0daeaaf419ff0ec310e27d1feb7c61772a9c4a9",
          "sha256": "71abe454726b78aedff49925f2cc792ed95152ccda32c7dfdbd6bc47cc70d091",
          "sha1": "19310a05446a2ad1a27d9abf3f4ec8ec63388c27",
          "md5": "93a6e3d579924ebe5dfaadd6b8a73cba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-lifecycle-1.1.0-beta02-sources.jar",
          "url": "camera-lifecycle-1.1.0-beta02-sources.jar",
          "size": 17027,
          "sha512": "6fba3df40acd2546709d4e870a7b81efc6fc36b34faa5a6646fdeb78faa90835ac3c74358a42c2a4fd9b189f57057999bfbce89d853aff6930c4b47ac723e1de",
          "sha256": "da7fef5c42bdb7975bcb7f8ad75345cbaf49b93182d71d1569982c3bb5932ac5",
          "sha1": "7ffca79e4b39ed49c5ca33f079e01b06a483d921",
          "md5": "52e4bc4e0f39c63d8399274fe7a74cd1"
        }
      ]
    }
  ]
}
