{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-extensions",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.1.0-beta02.aar",
          "url": "camera-extensions-1.1.0-beta02.aar",
          "size": 85941,
          "sha512": "e6dce3d049d0c2467018f40246114b53b1cb15cca8d40e1d2ac81d15e5b75273b3f8fa5aa6b9b5aca53fda3682e2d78cfcd31779c2f636dd4b32041d736bc2b2",
          "sha256": "02d01d38d032f9a0d2458ba998c866814410f7de72eb9b0e5c9b0bd5e9433c28",
          "sha1": "8f67b4c6e5f0e8543ac5aaa36103b12a3ff2fde4",
          "md5": "c088d5d3ac60f60db16ad98d4e1abb39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.1.0-beta02.aar",
          "url": "camera-extensions-1.1.0-beta02.aar",
          "size": 85941,
          "sha512": "e6dce3d049d0c2467018f40246114b53b1cb15cca8d40e1d2ac81d15e5b75273b3f8fa5aa6b9b5aca53fda3682e2d78cfcd31779c2f636dd4b32041d736bc2b2",
          "sha256": "02d01d38d032f9a0d2458ba998c866814410f7de72eb9b0e5c9b0bd5e9433c28",
          "sha1": "8f67b4c6e5f0e8543ac5aaa36103b12a3ff2fde4",
          "md5": "c088d5d3ac60f60db16ad98d4e1abb39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-extensions-1.1.0-beta02-sources.jar",
          "url": "camera-extensions-1.1.0-beta02-sources.jar",
          "size": 63884,
          "sha512": "d3d77097b3d527e55861662a299d398693519f0c560dd7eb898ea72366f5ce66ede2ab36de7d21227f0560972be505faf88879b409a1ddc05ea36152ab35895c",
          "sha256": "d7a89aa426298a9281727c54d3546f2d481be4a8412962b38495992f6ce270a4",
          "sha1": "124f86445962005d2da02506e723b33827c475a3",
          "md5": "9bf9e111248435c8cb4d49c39f157228"
        }
      ]
    }
  ]
}
