{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7210674"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.3.2.aar",
          "url": "fragment-1.3.2.aar",
          "size": 297065,
          "sha512": "8ea80a3e4743c53a33c18f1b01cb719233e711956a7d3dae900bb20e61bc38866937d4eff4d8b34c6d380fecd9afced8d5b89bf9b8aa9f7105ead65d2f172e49",
          "sha256": "299879e2ce39d35214391db4ef2d7257a801f9b7fbe76488cc64897d16a98b25",
          "sha1": "e0b78107a7b0681642d85805729f3f6c44a94a6b",
          "md5": "4a77772d4483749a0f63048ed5d810b8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.3.2.aar",
          "url": "fragment-1.3.2.aar",
          "size": 297065,
          "sha512": "8ea80a3e4743c53a33c18f1b01cb719233e711956a7d3dae900bb20e61bc38866937d4eff4d8b34c6d380fecd9afced8d5b89bf9b8aa9f7105ead65d2f172e49",
          "sha256": "299879e2ce39d35214391db4ef2d7257a801f9b7fbe76488cc64897d16a98b25",
          "sha1": "e0b78107a7b0681642d85805729f3f6c44a94a6b",
          "md5": "4a77772d4483749a0f63048ed5d810b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-1.3.2-sources.jar",
          "url": "fragment-1.3.2-sources.jar",
          "size": 183721,
          "sha512": "3cadace57f9b3b6b0e5ef72510b65bd1b8ddb62cf3b4ea01713bcb5934dcfaec1725b94db56c8555edfd4f6f1415d8a234d9c52891c42565190e468e61d04d59",
          "sha256": "d04cb7b1f924087d056ce4c754c79a907b09660baa623f48fe942bdd42a557eb",
          "sha1": "38ff84d3edb69f7173bb013ab00338a29799bcf4",
          "md5": "a60a531fc61dabfaf9ef8bb97932496c"
        }
      ]
    }
  ]
}
