{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.1.0-beta02.aar",
          "url": "camera-core-1.1.0-beta02.aar",
          "size": 576908,
          "sha512": "eb0fe8ed3d1a6337b54b5b9f4009ff55631a0b8c82fb70f3397286ce85fdf55f811a29b829d23a5002e9c3668cf23a7965b0b5650456a66b79fe47d9cab497d8",
          "sha256": "7332cc2cda75ae31d0ed6b1575659ae58e2e94596139ce7eb57c4e4d606a526e",
          "sha1": "597421b12670251f8dca5a331e68d0b7bddaaa02",
          "md5": "81a6531215aae38933b5776d4a85d838"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.1.0-beta02.aar",
          "url": "camera-core-1.1.0-beta02.aar",
          "size": 576908,
          "sha512": "eb0fe8ed3d1a6337b54b5b9f4009ff55631a0b8c82fb70f3397286ce85fdf55f811a29b829d23a5002e9c3668cf23a7965b0b5650456a66b79fe47d9cab497d8",
          "sha256": "7332cc2cda75ae31d0ed6b1575659ae58e2e94596139ce7eb57c4e4d606a526e",
          "sha1": "597421b12670251f8dca5a331e68d0b7bddaaa02",
          "md5": "81a6531215aae38933b5776d4a85d838"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-core-1.1.0-beta02-sources.jar",
          "url": "camera-core-1.1.0-beta02-sources.jar",
          "size": 430261,
          "sha512": "72dc8645dddaa76f0d9485007279a8e84cb0c64a3d38cc1a30feedda449691e5c9f52a829c7f3d489490ea2377d67cb92678631e2bec5dcf6a95d5a8bcf4ef4f",
          "sha256": "cd915a567531a341adcc3732b550275faca63369d9688613f1c1d1a10405f9bb",
          "sha1": "eb6a600f0c16ce18a7acf71d66f7bd36e2cda55e",
          "md5": "8a9e4dc9973ea06f16107d88d1e40eae"
        }
      ]
    }
  ]
}
