{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.1.0-beta02.aar",
          "url": "camera-camera2-1.1.0-beta02.aar",
          "size": 344032,
          "sha512": "09572212966b100bd619532f6ad0fce0c713b53022b1ebeb6ad07bcc02325cd0aff0d1c823ef7d0d5a3204b9dcb7e5906a96a95942b5a1174f315dddf2915bb9",
          "sha256": "ffd6850954aec156d19aca5e03a9c311781bda6efb831a8f855d4d2e720aaa57",
          "sha1": "6a53a7fd8862e62a1be0b3aead437de2f2f7ec78",
          "md5": "ca15fcd4db17558849d1a2b577ce91ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.1.0-beta02.aar",
          "url": "camera-camera2-1.1.0-beta02.aar",
          "size": 344032,
          "sha512": "09572212966b100bd619532f6ad0fce0c713b53022b1ebeb6ad07bcc02325cd0aff0d1c823ef7d0d5a3204b9dcb7e5906a96a95942b5a1174f315dddf2915bb9",
          "sha256": "ffd6850954aec156d19aca5e03a9c311781bda6efb831a8f855d4d2e720aaa57",
          "sha1": "6a53a7fd8862e62a1be0b3aead437de2f2f7ec78",
          "md5": "ca15fcd4db17558849d1a2b577ce91ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-1.1.0-beta02-sources.jar",
          "url": "camera-camera2-1.1.0-beta02-sources.jar",
          "size": 262801,
          "sha512": "f4f878cdc0a23e2e11dd49b187a0a880b9dee688a260c6a9e2eaf15bd744ef7f33d69da71be9fcb50a3850c4e4b0874f1de51fb95df79a5db964c1085d4fcc9f",
          "sha256": "84298a7ffb99df2c1d430ac9b87c8adfc1124482bd0aa93dcb0e12b8a59aea64",
          "sha1": "b30bc56295e81b4183c24024d0b9d7ef21dd7190",
          "md5": "6c90d9ac43752892e222664c583248c5"
        }
      ]
    }
  ]
}
