{
  "formatVersion": "1.1",
  "component": {
    "group": "com.firebaseui",
    "module": "firebase-ui-firestore",
    "version": "8.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.firebaseui",
          "module": "firebase-ui-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-firestore"
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-firestore-8.0.1.aar",
          "url": "firebase-ui-firestore-8.0.1.aar",
          "size": 26914,
          "sha512": "fe43e2ad9addf484850ef4a81f35f286357d39061969a1b54bc8274e30dafcd54d42d6077cf6ed2c24d3bcab99d2fde956d50bb20bf7de049c0c2a085ad048b7",
          "sha256": "81f25b66a36b4389adc9e632069d7e571ba6305903239bb7759d4c81bc7e706a",
          "sha1": "a736f1a3074a6eed3ac7eb67b63d38452165e266",
          "md5": "a7c0521a349f58c8841281e4d98caaeb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "28.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.firebaseui",
          "module": "firebase-ui-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-firestore"
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-firestore-8.0.1.aar",
          "url": "firebase-ui-firestore-8.0.1.aar",
          "size": 26914,
          "sha512": "fe43e2ad9addf484850ef4a81f35f286357d39061969a1b54bc8274e30dafcd54d42d6077cf6ed2c24d3bcab99d2fde956d50bb20bf7de049c0c2a085ad048b7",
          "sha256": "81f25b66a36b4389adc9e632069d7e571ba6305903239bb7759d4c81bc7e706a",
          "sha1": "a736f1a3074a6eed3ac7eb67b63d38452165e266",
          "md5": "a7c0521a349f58c8841281e4d98caaeb"
        }
      ]
    }
  ]
}
